// SculptCore — Multires: a stack of Catmull-Clark subdivision levels.
//
// Level 0 is stored as a complete PolyData. Every higher level stores only
// per-vertex detail: the offset from the subdivided lower level, expressed in
// a local tangent frame, so details ride along when lower levels change.
// Topology, UVs and face attributes of the higher levels are regenerated by
// subdivision, which keeps the stack small (and fast to save).
//
// Edits made at a level are written back with commit(): lower levels pick up
// the smoothed (large-scale) part of the change, higher levels follow
// automatically through their tangent-space details.
//
// The mask, SculptGroups and visibility are stored once, at the level where
// they were last edited, and converted when another level is built (up:
// inherited / averaged, down: taken from the matching vertices / first child).
#pragma once

#include <cstdint>
#include <string>
#include <vector>

#include "sculpt/poly.h"
#include "sculpt/subdivide.h"

namespace sculpt {

class Multires {
public:
    static constexpr int kMaxLevel = 6;

    // Starts a stack whose level 0 is `base` (topology, attributes and maps).
    bool reset(PolyData base, std::string* error = nullptr);
    bool empty() const { return base_.positions.empty(); }

    int topLevel() const { return static_cast<int>(levels_.size()); }
    const PolyData& base() const { return base_; }
    SubdivOptions levelOptions(int level) const;  // Options used to create `level` (>= 1).

    // Vertex / face counts of a level without building it.
    std::uint64_t vertexCount(int level) const;
    std::uint64_t faceCount(int level) const;

    // Builds level `level`: topology, attributes, maps and positions.
    bool build(int level, PolyData& out, std::string* error = nullptr) const;

    // Stores the edited mesh of `level` (same topology as build(level)).
    bool commit(int level, const PolyData& edited, std::string* error = nullptr);

    // Adds a level above the top one.
    bool addLevel(const SubdivOptions& options, std::string* error = nullptr);
    // `level` becomes level 0 (everything below is dropped).
    bool deleteLower(int level, std::string* error = nullptr);
    // Drops every level above `level`.
    bool deleteHigher(int level);
    // Rebuilds a coarser level 0 below the current base (fails if the base
    // is not a subdivided quad mesh).
    bool reverseSubdivision(std::string* error = nullptr);

    // Compact binary form (details stored as half floats).
    std::vector<std::uint8_t> serialize() const;
    bool deserialize(const std::uint8_t* data, std::size_t size, std::string* error = nullptr);
    std::size_t memoryBytes() const;

private:
    struct Level {
        SubdivOptions options;
        std::vector<Vec3> detail;  // Tangent-space offsets, one per vertex of this level.
    };
    struct Attributes {
        int level = 0;  // Level whose topology the arrays below match.
        std::vector<float> mask;
        std::vector<std::int32_t> groups;
        std::vector<std::uint8_t> hidden;
    };
    // Topology + positions of levels 0..level (positions absolute); the last
    // entry also carries the mask/groups/visibility converted to `level`.
    bool buildChain(int level, bool withMaps, std::vector<PolyData>& chain, std::string* error) const;
    void injectAttributes(PolyData& p) const;
    // Converts stored attributes of a higher level down to `level` (no-op otherwise).
    void attributesForLevel(int level, PolyData& out) const;
    static constexpr std::uint64_t kUnknownCount = ~std::uint64_t(0);

    PolyData base_;              // Level 0 (its mask/groups/hidden are unused: see attributes_).
    std::vector<Level> levels_;  // levels_[i] is level i + 1.
    Attributes attributes_;
    mutable std::uint64_t baseEdgeCount_ = kUnknownCount;
};

// Tangent frame of every vertex: normal from the polygon normals, tangent
// towards the vertex's first neighbour (deterministic for a topology).
struct TangentFrame {
    Vec3 t, b, n;
};
void computeTangentFrames(const PolyData& topology, const std::vector<Vec3>& positions, std::vector<TangentFrame>& frames);

}  // namespace sculpt
