// Resource IDs for SculptMesh.rc.
#pragma once

// Strings
#define IDS_LIB_DESCRIPTION 1
#define IDS_CLASS_NAME 2
#define IDS_CATEGORY 3
#define IDS_OBJECT_NAME 4
#define IDS_ROLLUP_TITLE 5
#define IDS_UNDO_STROKE 6
#define IDS_UNDO_CONVERT 7
#define IDS_PROMPT_SCULPT 8
#define IDS_ERR_SELECT_ONE 9
#define IDS_ERR_CANNOT_CONVERT 10
#define IDS_BRUSH_SCULPT 11
#define IDS_BRUSH_SMOOTH 12
#define IDS_BRUSH_INFLATE 13
#define IDS_BRUSH_PINCH 14
#define IDS_INFO_FORMAT 15
#define IDS_FP_DESCRIPTION 16

// Dialogs
#define IDD_SCULPT_PANEL 101

// Controls
#define IDC_SCULPT_BUTTON 1001
#define IDC_BRUSH_COMBO 1002
#define IDC_ADD_RADIO 1003
#define IDC_SUB_RADIO 1004
#define IDC_SIZE_EDIT 1005
#define IDC_SIZE_SPIN 1006
#define IDC_STRENGTH_EDIT 1007
#define IDC_STRENGTH_SPIN 1008
#define IDC_SPACING_EDIT 1009
#define IDC_SPACING_SPIN 1010
#define IDC_FALLOFF_CHECK 1011
#define IDC_BACKFACE_CHECK 1012
#define IDC_INFO_TEXT 1013
#define IDC_HELP_TEXT 1014

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif
