// Resource IDs for SculptMesh.rc.
#pragma once

// Strings
#define IDS_LIB_DESCRIPTION 1
#define IDS_CLASS_NAME 2
#define IDS_CATEGORY 3
#define IDS_OBJECT_NAME 4
#define IDS_UNDO_STROKE 6
#define IDS_UNDO_CONVERT 7
#define IDS_PROMPT_SCULPT 8
#define IDS_ERR_SELECT_ONE 9
#define IDS_ERR_CANNOT_CONVERT 10
#define IDS_INFO_FORMAT 15
#define IDS_FP_DESCRIPTION 16
#define IDS_UNDO_TRANSFORM 17
#define IDS_UNDO_MASK 18
#define IDS_UNDO_GROUPS 19
#define IDS_UNDO_VISIBILITY 20
#define IDS_ERR_SELECT_BASE 21
#define IDS_ERR_NO_MASK 22
#define IDS_PROMPT_LINE_START 23
#define IDS_ROLLUP_MULTIRES 24
#define IDS_OPEN_MENUS 25
#define IDS_CLOSE_MENUS 26
#define IDS_MULTIRES_HELP 27
#define IDS_ACTION_TABLE 28
#define IDS_ACTION_CATEGORY 29
#define IDS_ACT_SLOT1 30
#define IDS_ACT_SLOT2 31
#define IDS_ACT_SLOT3 32
#define IDS_ACT_SLOT4 33
#define IDS_ACT_SLOT5 34
#define IDS_ACT_QUICK_MENU 35
#define IDS_ACT_MOVE 36
#define IDS_ACT_ROTATE 37
#define IDS_ACT_SCALE 38
#define IDS_ACT_GROUP_FROM_MASK 39
#define IDS_ACT_TOGGLE_MENUS 40
#define IDS_UNDO_LEVEL 41
#define IDS_ERR_LEVEL 42
#define IDS_ERR_SUBDIVIDE_TOP 43
#define IDS_ERR_TOO_DENSE 44
#define IDS_UNDO_SUBDIVIDE 45
#define IDS_UNDO_DELETE_LOWER 46
#define IDS_UNDO_DELETE_HIGHER 47
#define IDS_ERR_REVERSE 48
#define IDS_UNDO_REVERSE 49
#define IDS_SURFACE_NONE 50
#define IDS_SURFACE_OTHER 51
#define IDS_SURFACE_FORMAT 52
#define IDS_UNDO_NEW_LAYER 53
#define IDS_UNDO_DELETE_LAYER 54
#define IDS_UNDO_CLEAR_LAYER 55
#define IDS_UNDO_MOVE_LAYER 56
#define IDS_UNDO_BAKE_LAYERS 57
#define IDS_UNDO_LAYER_SETTINGS 58
#define IDS_UNDO_DISPLACE 59
#define IDS_ERR_LAYERS_LEVEL 60
#define IDS_ERR_DISPLACE_MAP 61
#define IDS_ROLLUP_DISPLACE 62

// Dialogs
#define IDD_MULTIRES 102
#define IDD_ROWS_ROLLUP 103

// Keyboard shortcut defaults
#define IDR_SCULPT_SHORTCUTS 201

// Controls
#define IDC_SCULPT_BUTTON 1001
#define IDC_INFO_TEXT 1013
#define IDC_HELP_TEXT 1014
#define IDC_MENUS_BUTTON 1015

// Action / accelerator command IDs (stored in users' hotkey files: never change)
#define ID_SCULPT_SLOT1 40001
#define ID_SCULPT_SLOT2 40002
#define ID_SCULPT_SLOT3 40003
#define ID_SCULPT_SLOT4 40004
#define ID_SCULPT_SLOT5 40005
#define ID_SCULPT_QUICK_MENU 40006
#define ID_SCULPT_MOVE 40007
#define ID_SCULPT_ROTATE 40008
#define ID_SCULPT_SCALE 40009
#define ID_SCULPT_GROUP_FROM_MASK 40010
#define ID_SCULPT_TOGGLE_MENUS 40011

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif
